spring:
  application:
    name: auth
  datasource:
    url: jdbc:mysql://localhost:3306/miniprojet
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  port: 8080

