spring:
  application:
    name: auth
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    driver-class-name: com.mysql.jdbc.Driver
    password: قخخف
    username: root
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  port: 8080

